import type { SurveyResponse } from './types'

export const responses: SurveyResponse[] = [
  {
    id: 'cq-jordan',
    pdv: 'AO Ciudad Quesada',
    respondent: 'Jordan Gamboa',
    contact: '61696339',
    date: '02 mayo 2026',
    answered: 23,
    total: 23,
    answers: {
      q01: ['Clientes de zonas rurales cercanas'],
      q02: ['¿Tiene garantía o cambio?'],
      q03: ['Estaba buscando algo específico'],
      q04: ['Quincena (días 14–16 y fin de mes)', 'Sábado todo el día'],
      q05: ['Ropa mujer', 'Calzado deportivo', 'Herramientas'],
      q06: ['Accesorio que se viralizó por boca a boca'],
      q07: 'Calzado · Ropa · Productos para el hogar',
      q08: 'Más de 10 personas',
      q09: ['Responder mensajes de WhatsApp uno por uno'],
      q10: ['WhatsApp Business'],
      q11: ['Tenemos respuesta automática básica'],
      q12: ['Publicaciones de Instagram', 'Publicaciones de Facebook', 'Mensajes de WhatsApp masivos'],
      q13: ['Reels mostrando productos con precio'],
      q14: ['Todo está bien — solo falta más alcance'],
      q15: 100,
      q16: ['Inventario muerto que ocupa espacio', 'Tráfico bajo en días específicos', 'Competencia agresiva en precio'],
      q17: 100,
      q18: ['Qué clientes son revendedores frecuentes', 'Qué empleado vende mejor cada categoría'],
      q19: 'Sí, manejo Instagram y Facebook directamente',
      q20: 100,
      q21: ['Que me traigan más tráfico nuevo', 'Que me muestren métricas claras de qué está funcionando'],
      q22: 'Full.',
    },
  },
  {
    id: 'cq-mauro',
    pdv: 'AO Ciudad Quesada',
    respondent: 'Mauro Araya',
    contact: '7202 6095',
    date: '01 mayo 2026',
    answered: 22,
    total: 23,
    answers: {
      q01: ['Mujeres 25–45 años de la zona', 'Hombres 25–45 años de la zona', 'Adultos mayores 50+ años', 'Clientes de zonas rurales cercanas'],
      q02: ['Está caro', 'No tienen mi talla'],
      q03: ['Pasé por aquí y me llamó la atención', 'Estaba buscando algo específico'],
      q04: ['Viernes mañana', 'Viernes tarde', 'Sábado todo el día'],
      q05: ['Ropa mujer', 'Ropa niño/niña', 'Calzado deportivo', 'Calzado casual/formal', 'Accesorios (gorras, mochilas)', 'Ropa hombre'],
      q06: ['No identifico ninguna sorpresa últimamente'],
      q07: 'Ropa · Calzado · Juguetería',
      q08: 'Más de 10 personas',
      q09: [
        'Coordinar entregas a domicilio',
        'Gestionar apartados / reservas',
        'Dar precios y disponibilidad por teléfono',
        'Coordinar con clientes que vienen a recoger',
        'Llevar control de pedidos en cuaderno o Excel',
        'Tomar fotos de producto para enviar a clientes',
        'Responder mensajes de WhatsApp uno por uno',
        'Reportar ventas al encargado / dueño',
      ],
      q10: [
        'WhatsApp normal (no Business)',
        'WhatsApp Business',
        'Sistema POS / punto de venta',
        'Excel / hojas de cálculo',
        'Cuaderno físico',
        'Instagram para responder mensajes',
        'Facebook Messenger',
      ],
      q11: ['Le respondemos al día siguiente cuando abrimos'],
      q12: ['Publicaciones de Instagram', 'Boca a boca entre clientes', 'Carteles físicos en la tienda', 'Publicaciones de Facebook'],
      q13: ['Reels mostrando productos con precio', 'Videos de "qué llegó hoy"', 'Lives o transmisiones en vivo', 'Posts de promoción con descuentos'],
      q14: ['No respondemos a tiempo los mensajes', 'El contenido no representa bien la tienda', 'No coordinamos con las otras tiendas', 'Las promos no llegan a la gente'],
      q15: null,
      q16: [
        'Inventario muerto que ocupa espacio',
        'Tráfico bajo en días específicos',
        'Personal con poca capacitación',
        'Competencia agresiva en precio',
        'Falta de promoción digital',
        'Cliente que no vuelve después de la primera compra',
        'No tener métricas claras de qué funciona',
        'No sé qué se está vendiendo en las otras tiendas',
      ],
      q17: 100,
      q18: [
        'Qué productos se devuelven más',
        'Qué horas tienen tráfico real vs. fantasma',
        'Qué empleado vende mejor cada categoría',
        'Qué promociones funcionaron de verdad históricamente',
      ],
      q19: 'Sí, manejo Instagram y Facebook directamente',
      q20: 100,
      q21: ['Que me ayuden a vender el inventario que tengo trabado'],
      q22: 'Videos que llamen verdaderamente la atención.',
    },
  },
  {
    id: 'florencia',
    pdv: 'AO Florencia',
    respondent: 'Encargada (sin registrar)',
    contact: '—',
    date: '01 mayo 2026',
    answered: 22,
    total: 23,
    answers: {
      q01: ['Mujeres 25–45 años de la zona', 'Adolescentes y jóvenes 15–24 años'],
      q02: ['¿Tiene garantía o cambio?', 'Está caro', 'Lo encuentro más barato en otro lado'],
      q03: ['Mi vecina/amiga me recomendó', 'Vengo cada vez que llega producto nuevo', 'Estaba buscando algo específico'],
      q04: ['Miércoles tarde', 'Jueves tarde', 'Viernes tarde', 'Quincena (días 14–16 y fin de mes)'],
      q05: ['Ropa mujer', 'Electrodomésticos / línea blanca', 'Hogar y deco'],
      q06: ['Accesorio que se viralizó por boca a boca', 'Voy a especificar al final'],
      q07: 'Calzado · Línea blanca · Mueblería',
      q08: '3–5 personas',
      q09: ['Coordinar con clientes que vienen a recoger', 'Dar precios y disponibilidad por teléfono', 'Gestionar apartados / reservas', 'Responder mensajes de WhatsApp uno por uno'],
      q10: ['WhatsApp normal (no Business)'],
      q11: ['Le respondemos al día siguiente cuando abrimos'],
      q12: ['Boca a boca entre clientes', 'Carteles físicos en la tienda'],
      q13: ['Videos de "qué llegó hoy"'],
      q14: ['No coordinamos con las otras tiendas', 'Las promos no llegan a la gente'],
      q15: 80,
      q16: ['Tráfico bajo en días específicos'],
      q17: 100,
      q18: ['Qué clientes habituales ya no vuelven'],
      q19: 'No sé quién tiene el acceso actualmente',
      q20: 100,
      q21: ['Que me traigan más tráfico nuevo', 'Que me posicionen mejor que la competencia local', 'Que me muestren métricas claras de qué está funcionando', 'Que comuniquen mejor las promociones que hago'],
      q22: 'Apoyo total a todo lo que deseen hacer para mejorar las ventas en la tienda y la fluencia de clientes.',
    },
  },
  {
    id: 'fortuna',
    pdv: 'AO Fortuna',
    respondent: 'Andrea Ledezma Rodriguez',
    contact: '60831719',
    date: '01 mayo 2026',
    answered: 20,
    total: 23,
    answers: {
      q01: ['Mujeres 25–45 años de la zona', 'Hombres 25–45 años de la zona', 'Adultos mayores 50+ años'],
      q02: ['¿Tiene garantía o cambio?', 'Lo encuentro más barato en otro lado'],
      q03: ['Vine porque lo vi en Instagram', 'Vengo cada vez que llega producto nuevo'],
      q04: ['Lunes tarde', 'Jueves tarde', 'Viernes tarde', 'Sábado todo el día', 'Quincena (días 14–16 y fin de mes)'],
      q05: ['Hogar y deco', 'Electrodomésticos / línea blanca', 'Ropa hombre', 'Ropa mujer'],
      q06: ['Producto de hogar inesperado', 'Herramienta o electrodoméstico que voló'],
      q07: 'Electrodomésticos · Hogar · Muebles',
      q08: '3–5 personas',
      q09: ['Tomar fotos de producto para enviar a clientes', 'Dar precios y disponibilidad por teléfono'],
      q10: ['WhatsApp Business', 'Sistema POS / punto de venta'],
      q11: ['Tenemos respuesta automática básica', 'Le respondemos al día siguiente cuando abrimos'],
      q12: ['Carteles físicos en la tienda', 'Mensajes de WhatsApp masivos', 'Boca a boca entre clientes'],
      q13: ['Videos de "qué llegó hoy"', 'Posts de promoción con descuentos'],
      q14: ['Las promos no llegan a la gente', 'Todo está bien — solo falta más alcance'],
      q15: null,
      q16: ['Inventario muerto que ocupa espacio', 'Falta de promoción digital', 'Personal con poca capacitación', 'Competencia agresiva en precio'],
      q17: null,
      q18: ['Qué empleado vende mejor cada categoría', 'Qué pregunta el cliente que entra y se va sin comprar', 'Qué clientes habituales ya no vuelven'],
      q19: 'No tengo acceso, lo hace otra persona',
      q20: null,
      q21: ['Que me muestren métricas claras de qué está funcionando', 'Que me ayuden a vender el inventario que tengo trabado', 'Que me traigan más tráfico nuevo', 'Que me posicionen mejor que la competencia local'],
      q22: 'Disponibilidad para aprender a manejar el marketing en redes. Compromiso para crear contenido que venda y atraiga más clientes.',
    },
  },
]

export const PDV_COLORS: Record<string, string> = {
  'AO Ciudad Quesada': '#ff6b2b',
  'AO Florencia': '#0ea5e9',
  'AO Fortuna': '#8b5cf6',
}

export const PDV_BG: Record<string, string> = {
  'AO Ciudad Quesada': 'rgba(255,107,43,0.1)',
  'AO Florencia': 'rgba(14,165,233,0.1)',
  'AO Fortuna': 'rgba(139,92,246,0.1)',
}

export const FILTER_LABELS: Record<string, string> = {
  all: 'Todos',
  'ciudad-quesada': 'Ciudad Quesada',
  florencia: 'Florencia',
  fortuna: 'Fortuna',
}
